### ISSUE TITLE
mod installation fails with "range end index 4 out of range for slice of length 0"

### ISSUE THREAD

**Issue by LisandraBrave** [NiceneNerd/ukmm#42]
Attempting to install zelda's ballad dialog and audio fixes fails with the error
```
thread '<unnamed>' panicked at 'range end index 4 out of range for slice of length 0', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/botw-utils-0.4.0/src/hashes.rs:76:17
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[2023-02-23T18:17:39Z ERROR ukmm::gui] range end index 4 out of range for slice of length 0
    
    Stack backtrace:
       0: <unknown>
       1: <unknown>
       2: <unknown>
       3: <unknown>
       4: start_thread
       5: __GI___clone3
range end index 4 out of range for slice of length 0
```

**Comment by NiceneNerd** [comment]
There is an empty file in the mod that probably shouldn't be there, but TBH it also shouldn't panic when that happens, so I'll figure a workaround.

**Comment by LisandraBrave** [comment]
Problem persists on c29c7a6 after running `cargo clean` and rebuilding
backtrace has a lot more information this time though
```
[2023-02-27T19:47:22Z ERROR ukmm::gui] range end index 4 out of range for slice of length 0
    
    Stack backtrace:
       0: anyhow::error::<impl anyhow::Error>::msg
       1: std::sys_common::backtrace::__rust_begin_short_backtrace
       2: core::ops::function::FnOnce::call_once{{vtable.shim}}
       3: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
                 at /rustc/07c993eba8b76eae497e98433ae075b00f01be10/library/alloc/src/boxed.rs:1988:9
       4: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
                 at /rustc/07c993eba8b76eae497e98433ae075b00f01be10/library/alloc/src/boxed.rs:1988:9
       5: std::sys::unix::thread::Thread::new::thread_start
                 at /rustc/07c993eba8b76eae497e98433ae075b00f01be10/library/std/src/sys/unix/thread.rs:108:17
       6: start_thread
       7: __GI___clone3

```

**Comment by bbugh** [comment]
Something similar is happening with Hyrule Rebalance v7.11, ukmm latest 0.7.1

https://gamebanana.com/mods/download/49532#FileInfo_970238

> range end index 92 out of range for slice of length 91
